version: "3.8"

services:

  accounts:
    image: ayozer/accounts:latest
    mem_limit: 700m #Doesn't work with docker-compose v3
    ports:
      - "8080:8080"
    networks:
      - ayozer-network

  loans:
    image: ayozer/loans:latest
    mem_limit: 700m #Doesn't work with docker-compose v3
    ports:
      - "8090:8090"
    networks:
      - ayozer-network

  cards:
    image: ayozer/cards:latest
    mem_limit: 700m #Doesn't work with docker-compose v3
    ports:
      - "9000:9000"
    networks:
      - ayozer-network

networks:
  ayozer-network: