version: "3.8"

services:

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - ayozer

  grafana:
    image: "ayozer/grafana-hazir:latest"
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password
    networks:
      - ayozer
    depends_on:
      - prometheus

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - ayozer

  configserver:
    image: ayozer/configserver:latest
    ports:
      - "8071:8071"
    networks:
      - ayozer
    depends_on:
      - zipkin
    environment:
      SPRING_PROFILES_ACTIVE: prod
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin:9411/api/v2/spans
      ENCRYPT_KEY: D@57ws!wA

  eurekaserver:
    image: ayozer/eurekaserver:latest
    ports:
      - "8070:8070"
    networks:
      - ayozer
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_APPLICATION_NAME: eurekaserver
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin:9411/api/v2/spans

  accounts:
    image: ayozer/accounts:latest
    ports:
      - "8080:8080"
    networks:
      - ayozer
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_APPLICATION_NAME: accounts
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/ #configserver is resolved by Docker
      #using the configserver service declared above...
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin:9411/api/v2/spans

  #  accounts1:
  #    image: ayozer/accounts:latest
  #    ports:
  #      - "8081:8080"
  #    networks:
  #      - ayozer
  #    depends_on:
  #      - configserver
  #      - eurekaserver
  #    deploy:
  #      restart_policy:
  #        condition: on-failure
  #        delay: 30s
  #        max_attempts: 3
  #        window: 120s
  #    environment:
  #      SPRING_APPLICATION_NAME: accounts
  #      SPRING_PROFILES_ACTIVE: default
  #      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/ #configserver is resolved by Docker
  #                                                                   #using the configserver service declared above...
  #      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/

  loans:
    image: ayozer/loans:latest
    ports:
      - "8090:8090"
    networks:
      - ayozer
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_APPLICATION_NAME: loans
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin:9411/api/v2/spans

  cards:
    image: ayozer/cards:latest
    ports:
      - "9000:9000"
    networks:
      - ayozer
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_APPLICATION_NAME: cards
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin:9411/api/v2/spans

  gatewayserver:
    image: eazybytes/gatewayserver:latest
    ports:
      - "8072:8072"
    networks:
      - ayozer
    depends_on:
      - configserver
      - eurekaserver
      - cards
      - loans
      - accounts
    deploy:
      restart_policy:
        condition: on-failure
        delay: 45s
        max_attempts: 3
        window: 180s
    environment:
      SPRING_APPLICATION_NAME: gatewayserver
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin:9411/api/v2/spans

networks:
  ayozer: