deploymentName: loans-deployment
deploymentLabel: loans
appName: loans

replicaCount: 2

image:
  repository: ayozer/loans
  tag: latest

containerPort: 8090

service:
  type: ClusterIP
  port: 8090
  targetPort: 8090

config_enabled: true
zipkin_enabled: true
profile_enabled: true
eureka_enabled: true
appname_enabled: true
keycloak_enabled: false