{{- define "common.deployment" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deploymentName }}
  labels:
    app: {{ .Values.deploymentLabel }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.deploymentLabel }}
  template:
    metadata:
      labels:
        app: {{ .Values.deploymentLabel }}
    spec:
      containers:
        - name: {{ .Values.deploymentLabel }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.containerPort }}
              protocol: TCP
          env:
          {{- if .Values.appname_enabled }}
          - name: SPRING_APPLICATION_NAME
            value: {{ .Values.appName }}
          {{- end }}
          {{- if .Values.profile_enabled }}
          - name: SPRING_PROFILES_ACTIVE
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMapName }}
                key: SPRING_PROFILE
          {{- end }}
          {{- if .Values.zipkin_enabled }}
          - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMapName }}
                key: ZIPKIN_ENDPOINT
          {{- end }}
          {{- if .Values.config_enabled }}
          - name: SPRING_CONFIG_IMPORT
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMapName }}
                key: CONFIG_SERVER
          {{- end }}
          {{- if .Values.eureka_enabled }}
          - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMapName }}
                key: EUREKA_CLIENT_URL
          {{- end }}
          {{- if .Values.resourceserver_enabled }}
          - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMapName }}
                key: JWKS_URI
          {{- end }}
          {{- if .Values.keycloak_enabled }}
          - name: SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_TOKEN-URI
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMapName }}
                key: TOKEN_URI
          {{- end }}
          {{- if .Values.keycloak_enabled }}
          - name: SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_AUTHORIZATION-URI
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMapName }}
                key: AUTHORIZATION_URI
          {{- end }}
          {{- if .Values.keycloak_enabled }}
          - name: SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_USER-INFO-URI
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.global.configMapName }}
                key: USERINFO_URI
          {{- end }}
          {{- if .Values.keycloak_enabled }}
          - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_AYOZER-GATEWAY_CLIENT-ID
            valueFrom:
              secretKeyRef:
                name: {{ .Values.global.secretName }}
                key: keycloakclientid
          {{- end }}
          {{- if .Values.keycloak_enabled }}
          - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_AYOZER-GATEWAY_CLIENT-SECRET
            valueFrom:
              secretKeyRef:
                name: {{ .Values.global.secretName }}
                key: keycloakclientsecret
          {{- end }}
{{- end -}}