deploymentName: cards-deployment
deploymentLabel: cards
appName: cards

replicaCount: 2

image:
  repository: ayozer/cards
  tag: latest

containerPort: 9000

service:
  type: ClusterIP
  port: 9000
  targetPort: 9000

config_enabled: true
zipkin_enabled: true
profile_enabled: true
eureka_enabled: true
appname_enabled: true
keycloak_enabled: false
resourceserver_enabled: false